apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "snowflake-poc.fullname" . }}-nginx-config
  labels:
    {{- include "snowflake-poc.labels" . | nindent 4 }}
data:
  default.conf: |-
    server {
        listen 80;
        server_name _;
        root /var/www/html/public;
    
        # Security headers
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        add_header Content-Security-Policy "default-src 'self'; script-src 'self'; img-src 'self'; style-src 'self'; font-src 'self'; connect-src 'self'; frame-ancestors 'none'; form-action 'self';" always;

        location / {
            try_files $uri /index.php$is_args$args;
        }

        location ~ ^/index\.php(/|$) {
            fastcgi_pass localhost:9000;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT $document_root;
            internal;
        }

        location ~ \.php$ {
            return 404;
        }

        # Logging
        access_log /dev/stdout;
        error_log /dev/stderr;
    }