apiVersion: v2
name: snowflake-poc
description: A Helm chart for Snowflake ID Generator Symfony POC
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Your Name
    email: your.email@example.com
dependencies:
  - name: postgresql
    version: ^12.1.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: rabbitmq
    version: ^11.9.0
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled